export const LOAD_PHONES = 'LOAD_PHONES';
export const FETCH_CATALOG = 'FETCH_CATALOG';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const GET_INFO_DETAIL = 'GET_INFO_DETAIL';
